{
 "title": "Gateway Metrics",
 "tags": [ "gateway" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Accepted Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(events_received_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processed Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(events_published_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(events_publish_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}